<main>
    <section class="contact">
        <div class="contacter">
            <div class="logo">
                <img src="./assets/images/<?= $data['logo'] ?>" alt="logo">
            </div>
            <h3>NOUS CONTACTER</h3>
            <ul>
                <li><svg src="./assets/images/facebook.svg" alt="facebook"></svg></li>
                <li><svg src="./assets/images/twitter.svg" alt="twitter"></svg></li>
                <li><svg src="./assets/images/instagram.svg" alt="instagram"></svg></li>
                <li><svg src="./assets/images/tik-tok.svg" alt="tik-tok"></svg></li>
                <li><svg src="./assets/images/youtube.svg" alt="youtube"></svg></li>
        </div>
    </section>
</main>