<section class="matchs">
    <div class="match_contenue">
        <h2>LES MATCHS</h2>
        
        <?php 
        
        foreach($data['matches'] as $game) 
        { ?>
            <div class="match">
                <h3><?= $game->getName() ?></h3>
                <p><?=$game->getDate() ?></p>
                <div class="match_img">
                    
                    <img src="<?=$teams[$game->getTeam1()]->getLogo() ?>" alt="">
                    <img src="<?=$teams[$game->getTeam2()]->getLogo() ?>" alt="">
                </div>
                
                
                
                <a href="?route=match&id=<?= $game->getId() ?>" class="button_detail">
                    <button type="button">Détails du match</button>
                </a>
                
            </div>
        <?php } ?>
    </div>
</section>