<section class="teams">
    <div class="contenue_teams">
        <h2>LES TEAMS DE LA LEAGUE</h2>
        <div class="vrap_teams">
            <?php foreach($data['teams'] as $team)
                { ?>
            <div class="column_teams">
                <img src="<?= $team->getLogo() ?>" alt="all teams">
                <h3><?= $team->getName() ?></h3>
                <h4><?= $team->getDescription() ?></h4>
                <a href="?route=team&id=<?= $team->getId() ?>" class="button_detail">
                    <button type="button">Découvrez <?= $team->getName() ?></button>
                </a>
            </div>
            <?php } ?>
        </div>
    </div>
</section>