<section class="player-performances">
    <div class="contenu_pp">
    <h2>SES PERFORMANCES</h2>

    <?php if (!empty($stats)) { ?>
        
        <table class="stats-table">
            <thead>
                <tr>
                    <th class="col-yellow">TEAM ADVERSE</th>
                    <th>POINTS</th>
                    <th>ASSISTS</th>
                    <th>VICTOIRE ?</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($stats as $stat) { ?>
                    <?php 
                    
                        foreach($games as $game) {
                            if ($game->getId() == $stat->getGameId()) {
                                $gam = $game;
                            }

                        }
                        if ($gam->getWinner() == $player->getTeam())
                        { 
                            $truc = "oui";
                        } 
                        else 
                        {
                            
                            $truc = "non";
                        }
                        ?>
                    <tr>
                    <td class="nom_match"><?= $stat->getGameName() ?></td>
                    
                    <td><?= $stat->getPoints() ?></td>
                    
                    <td><?= $stat->getAssists() ?></td>
                    
                    <td class="col-green"><?= $truc?></td> 
                </tr>
                <?php } ?>
            </tbody>
        </table>

    <?php } else { ?>
        <p class="no-stats">Aucune performance enregistrée.</p>
    <?php } ?>
    </div>
</section>