<main>
    <section class="dernier">
        <h2>LE DERNIER MATCH</h2>
        <div class="matche_du_jour">
            
            <?php 
                $winnerId = (int)$matches[0]->getWinner(); 
                $team1Id  = (int)$matches[0]->getTeam1();
                $team2Id  = (int)$matches[0]->getTeam2();

                $classTeam1 = '';
                $classTeam2 = '';

                if ($winnerId !== 0) {
                    if ($winnerId === $team1Id) {
                        $classTeam1 = 'winner';
                    } elseif ($winnerId === $team2Id) {
                        $classTeam2 = 'winner';
                    }
                }
            ?>
            <h3><?=$matches[0]->getName() ?></h3>

            <p><?=$matches[0]->getDate() ?></p>
            <div class="img_matche_du_jour">
                <img src="<?=$teams[$matches[0]->getTeam1()]->getLogo() ?>" alt="Team 1" class="<?= $classTeam1 ?>">

                <img src="<?=$teams[$matches[0]->getTeam2()]->getLogo() ?>" alt="Team 2" class="<?= $classTeam2 ?>">
            </div>
        </div>
    </section>
</main>