<main>
    <section class="team_une">
        <h2>TEAM À LA UNE</h2>
        <div class="row_une"> 
            <img class="img_une" src="<?= $teams[0]->getLogo(); ?>" alt="">
            <div class="column_une">
                <h3><?= $teams[0]->getName(); ?></h3>
                <p>Les players</p>
                <div class="for_une">
                <?php foreach ($teams[0]->getPlayers() as $player){ ?>
                    <div class="team_tuiles">
                        <img src="<?= $player->getPortrait() ?>" alt="" >
                        <p><?= $player->getNickname() ?></p>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </section>

<section class="player_une">
    <h2>LES PLAYERS À LA UNE</h2>
    <div class="row2_une"> 
        <?php 
        $idsChoisis = [3, 12, 14]; 

        foreach($players as $player):
            if (in_array($player->getId(), $idsChoisis)):{
        ?>
            <div class="player_tuiles">
                <img class="img_perso_une" src="<?= $player->getPortrait() ?>" alt="<?= $player->getNickname() ?>">
                
                <h3><?= $player->getNickname() ?></h3>
                
                <?php /* <h4>Team #<?= $player_une->getTeam() ?></h4> */ ?>
                <?php } ?>
            </div>
        <?php 
            endif; 
        endforeach; 
        ?>
    </div>
</section>
</main>
