<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=a-propos">À propos</a>
					</li>
                    <li>
						<a href="index.php?route=contact">Contact</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
			if($route === "home")
            {
                require "templates/home.phtml";
            }

            else if($route === "team")
            {
                require "templates/team.phtml";
            }

            else if($route === "player")
            {
                require "templates/player.phtml";
            }

            else if($route === "match")
            {
                require "templates/match.phtml";
            }

            else
            {
                require "templates/notFound.phtml";
            }
		?>
	</body>
</html>